### ISSUE TITLE
Latest release (0.15.0) missing from repo

### ISSUE THREAD

**Issue by jdhoek** [Yubico/java-u2flib-server#18]
It seems version `0.15.0` was never mirrored to this repo. Could it be out of sync with Yubico's internal git repository?

I would like to submit a PR, but I would like to test it against an up-to-date master if possible.

**Comment by dainnilsson** [comment]
I'm currently looking in to this. The main developer previously working on this project has left the company. 0.15.0 was released in March 2015, and several commits have been added since. It seems that the changes made to the pom.xml files to set the 0.15.0 version were lost (maybe they were done in a local branch or something), and not noticed until now. Anyway, I have now bumped the version to 0.16.0-SNAPSHOT. As far as I know the code in this repo is the most up-to-date version available.

**Comment by jdhoek** [comment]
Great, thanks for looking into this.
