### ISSUE TITLE
Publish SoftKey.java as a test-jar?

### ISSUE THREAD

**Issue by vanDonselaar** [Yubico/java-u2flib-server#32]
I would like to write an integration test for my API that supports U2F. Is it possible to also release a test-jar containing the soft key implementation (`com.yubico.u2f.softkey.SoftKey`)?

**Comment by emlun** [comment]
Hi, sorry for the late response. I don't think we have the resources to support releasing a proper test library, especially since the tester's needs are likely to vary a lot with the circumstances of the test. You are of course welcome to copy `SoftKey.java` under the terms of the BSD license, or implement your own with ours (actually it looks like that class was originally written by Google, not us) as a guide.

I'll close this with no action, but please feel free to reopen it if you have any further questions.
