### ISSUE TITLE
Unable to build with JDK 10 or JDK 11-ea

### ISSUE THREAD

**Issue by FibreFoX** [Yubico/java-u2flib-server#38]
Hi there,

as I'm researching the usage of 2FA using a Yubikey, I came across this project. For a long-term solution and having the fading JDK 8 support, I tried to compile this project on a Windows 10 machine using Maven with JDK 10 and JDK 11-ea.

**JDK 10**
```
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T09:58:13+02:00)
Maven home: C:\maven\apache-maven-3.5.2\bin\..
Java version: 10, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk-10
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**JDK 11-ea**
```
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T09:58:13+02:00)
Maven home: C:\maven\apache-maven-3.5.2\bin\..
Java version: 11-ea, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk-11
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

The project does not compile, upgrading several dependencies, I'm not finding a quick way for having this project being usable from source.

Please update this project, or state what is required to have a proper setup to build this project.

One more question: why having mixed tooling-support Maven and Gradle?

**Comment by emlun** [comment]
Thanks for the report! Sorry for the late response.

First off: if you're planning a new deployment, we recommend instead looking at our [java-webauthn-server][jws] library. [WebAuthn][webauthn] is planned to supersede U2F, so for new deployments we recommend looking at using that instead. This library is set to be deprecated (sorry we haven't added a notice of it yet), and active development of this project will stop once java-webauthn-server version 1.0.0 is released.

If you still need JDK 10 and/or 11 support, let me know and I'll take a look at it. Both `mvn verify` and `./gradlew check` work as expected under JDK 8, at least.

The reason for mixed tooling support is that we were considering migrating to Gradle but didn't make the decision to drop the Maven stuff, and there's been very little active development on the project since.

[jws]: https://github.com/Yubico/java-webauthn-server/
[webauthn]: https://www.w3.org/TR/webauthn/

**Comment by emlun** [comment]
As stated above, let me know if you need further action on this. You're welcome to re-open the issue in that case.
